### ISSUE TITLE
Error while writing file

### ISSUE THREAD

**Issue by win4r** [GuillaumeMCK/PyPass-SAB#2]
![image](https://user-images.githubusercontent.com/42172631/220115762-6443b6fe-ad5c-4add-86d5-18d1218d13a3.png)

![image](https://user-images.githubusercontent.com/42172631/220115664-ecbc4502-af57-45ee-80ec-1cac519463ec.png)

**Comment by GuillaumeMCK** [comment]
You have selected the wrong file... The file to patch is not python3.dll but StartAllBackX64.dll. As the default path to the file (C:\Program Files\StartAllBack\StartAllBackX64.dll) was not found you must define the correct path.

**Comment by ghost** [comment]
> [@win4r](https://github.com/win4r) you have selected the wrong file... The file to patch is not python3.dll but StartAllBackX64.dll. As the default path to the file (C:\Program Files\StartAllBack\StartAllBackX64.dll) was not found you must define the correct path.

?
