### ISSUE TITLE
Feature request: StartIsBack addon

### ISSUE THREAD

**Issue by hkpD** [GuillaumeMCK/PyPass-SAB#3]
Hello,

Are you able to make a version of this for the StartIsBack program for Windows 10? It would be extremely useful.

Thanks

**Comment by GuillaumeMCK** [comment]
Hi,

I'm sorry, but I don't have access to a Windows 10 environment. As a result, setting up a virtual machine to work on this project would be quite time-consuming for me.  However, I'll do my best to assist you if you decide to tackle it on your own.

Best regards.
